### ISSUE TITLE
Connecticut CT State Library

### ISSUE THREAD

**Issue by mabnyc** [tom5760/ezproxy-db#131]
### Name

CT State Library

### URL

https://login.cslib.idm.oclc.org/login?qurl=$@

### Country

USA

**Comment by mabnyc** [comment]
is there a way for me to test this?

**Comment by tom5760** [comment]
> is there a way for me to test this?

In the extension preferences, you can insert a custom URL to test.  It seems ok though, so I'm going to add it to the database.  Feel free to submit an update if you see anything wrong with it.

Thanks for the contributions!

**Comment by tom5760** [comment]
This and #132 have been added to the database.  Thanks for the contribution @mabnyc!
