### ISSUE TITLE
Please change University of Portland Proxy URL

### ISSUE THREAD

**Issue by hseniorGIT** [tom5760/ezproxy-db#29]
**What is the name of the school / institution?**
University of Portland

**What is the new proxy URL?**
The URL **MUST** include `$@`, to signal where the proxied URL should go.  For example: `http://www.library.drexel.edu/cgi-bin/r.cgi?url=$@`

https://login.uportland.idm.oclc.org/login?url=$@

**Comment by tom5760** [comment]
Site has been updated.  Thanks @hseniorGIT!
