### ISSUE TITLE
Can't edit urls?

### ISSUE THREAD

**Issue by pitakakariki** [tom5760/ezproxy-db#3]
The url for University of Otago doesn't seem to be working any more.

If I try to submit a new one - `https://ezproxy.otago.ac.nz/login?url=$@` - I get the error: "A proxy with that name already exists in the database, please try again."

**Comment by tom5760** [comment]
Thanks for the report!  Yeah, unfortunately the way I did this at first requires the names to be different.  A work-around would be to put some word, like "UPDATED", on the end of the university name.  I'll see that when I go to approve the URL, and make the update manually.

Hopefully sometime soon I'll find the time to make this a bit saner.

**Comment by erinrwhite** [comment]
A +1 for this request. Our Proxy URL for Virginia Commonwealth University is now https rather than http.

and...**thank you** for your work on this! We are promoting this add-on to our campus community.

**Comment by tom5760** [comment]
Definitely still on the list...  Sorry for the delay!

I've updated the URL for Virginia Commonwealth University with that change.

Thanks for the comment!  I do have a few other improvements in mind for a future update.

**Comment by erinrwhite** [comment]
thanks so much!!!

**Comment by 00sapo** [comment]
Hello, There exist 2 entries for "Università di Milano" and "Universita degli Studi di Milano". I think that only the second one is correct

**Comment by tom5760** [comment]
Thanks @00sapo, I've updated the database.  Thanks!
