### ISSUE TITLE
Universidad de Guadalajara

### ISSUE THREAD

**Issue by pauutorres** [tom5760/ezproxy-db#33]
**What is the name of the school / institution?**
Universidad de Guadalajara

**What is the proxy URL?**
The URL **MUST** include `$@`, to signal where the proxied URL should go.  For example: `http://www.library.drexel.edu/cgi-bin/r.cgi?url=$@`
https://www.wdg.biblio.udg.mx:8443/login?url=$@
https://wdg-biblio-udg-mx.wdg.biblio.udg.mx:8443/
https://wdg-biblio-udg-mx.wdg.biblio.udg.mx:8443/index.php/paginaacceso
https://wdg-biblio-udg-mx.wdg.biblio.udg.mx:8443/login?url=$@

**Comment by tom5760** [comment]
Hello @pauutorres, which of these URLs should I use?  If they are different, whats the difference between them?

**Comment by pauutorres** [comment]
No estoy segura cual es la correcta, pero segun yo es esta
https://wdg-biblio-udg-mx.wdg.biblio.udg.mx:8443/login?url=$@

**Comment by tom5760** [comment]
The website has been updated.  Thanks @pauutorres!
