### ISSUE TITLE
Safari option?

### ISSUE THREAD

**Issue by tzehuilee** [tom5760/ezproxy-db#4]
Can you also make a safari version as well? Many thanks

**Comment by tom5760** [comment]
Hi!  I assume you are talking about the [Chrome & FIrefox extension](https://github.com/tom5760/chrome-ezproxy), right?  I currently don't have any Apple hardware, so would be pretty tough for me to do that.  The code is all up there though, I'd be happy to accept any pull requests to make it work there.
