### ISSUE TITLE
King Fahd University of Petroleum & Minerals (KFUPM)

### ISSUE THREAD

**Issue by asifaltaf1987** [tom5760/ezproxy-db#42]
**What is the name of the school / institution?**
King Fahd University of Petroleum & Minerals (KFUPM)

**What is the new proxy URL?**
https://login.kfupm.idm.oclc.org/login?url=$@

**Comment by tom5760** [comment]
Hello @asifaltaf1987, did you intend to close these tickets (#42, #43, #44)?  Do you still want these proxies listed?

**Comment by tom5760** [comment]
Please don't close these issues until I can actually update the database.  Thanks!
