### ISSUE TITLE
New Proxy URL

### ISSUE THREAD

**Issue by sawilson** [tom5760/ezproxy-db#50]
### Name

Toronto Metropolitan University

### URL

https://ezproxy.lib.torontomu.ca/login?url=$@

**Comment by sawilson** [comment]
Please add this new prozy url and remove the old one for Ryerson University https://ezproxy.lib.ryerson.ca/login?url=$@ as our university has changed its name and its ezproxy url.  Thanks.

**Comment by tom5760** [comment]
Updated.  Thanks @sawilson!
