### ISSUE TITLE
add proxy URL template for Seattle Public Library

### ISSUE THREAD

**Issue by lexical1** [tom5760/ezproxy-db#51]
### Name

Seattle Public Library

### URL

https://$encodeddns.ezproxy.spl.org/$path

**Comment by lexical1** [comment]
Example result URL: https://www-oed-com.ezproxy.spl.org/search?searchType=dictionary&q=jar&_searchBtn=Search

**Comment by lexical1** [comment]
Okay, looks like this can use

https://ezproxy.spl.org/login?url=$@

**Comment by tom5760** [comment]
Site should be updated now.  Thanks @lexical1!
