### ISSUE TITLE
Please update University of Central Florida to OpenAthens... again

### ISSUE THREAD

**Issue by cybrgrl** [tom5760/ezproxy-db#6]
**What is the name of the school / institution?**
University of Central Florida

**What is the new proxy URL?**
https://go.openathens.net/redirector/ucf.edu?url=@

I added an entry to for UCF's OpenAthens some time back, and then had a nice email conversation asking to remove the old EZproxy entry for us.  I think something must have gone awry, because the OpenAthens entry is gone and the incorrect EZproxy info is back. 

I hope you can update the entry soon.  I want to show EZproxy Redirect to the Dean of the Libraries!

Thanks,
Athena

Athena Hoeppner
Discovery Services Librarian
University of Central Florida
athena@ucf.edu

**Comment by tom5760** [comment]
I must have gotten confused when I was moving things over to this new setup.  Sorry!  It's fixed now.  Thanks for the update!

**Comment by cybrgrl** [comment]
Thanks for the uber speedy response!
