### ISSUE TITLE
Rochester Institute of Technology EZProxy URL

### ISSUE THREAD

**Issue by vg** [tom5760/ezproxy-db#70]
### Name

Rochester Institute of Technology

### URL

http://ezproxy.rit.edu/login?url=$@

**Comment by tom5760** [comment]
Turns out, we [already had this](https://github.com/tom5760/ezproxy-db/blob/40ca952a43942fe7a445abe462cca947c7455be4/static/proxies.json#L3270-L3273), but it was just named "RIT".  I've renamed it to the full "Rochester Institute of Technology".  Thanks @vg!

**Comment by vg** [comment]
Interesting, I did search for "RIT", but nothing showed up.
