### ISSUE TITLE
University of Auckland EZProxy replaces "." with "-" and splits proxied URL

### ISSUE THREAD

**Issue by janerallison** [tom5760/ezproxy-db#78]
### Name

University of Auckland

### URL

https://$@[! periods in domain name replaced by dashes].ezproxy.auckland.ac.nz/$@[! rest of URL]

**Comment by janerallison** [comment]
Sorry there was no space for comment earlier but I will try to describe what happens with an example (note that this seems to be a fairly recent change to the University of Auckland EXProxy access):

Original URL (no access):
https://pubs.acs.org/doi/abs/10.1021/acs.accounts.7b00613

Modified URL (with access):
https://pubs-acs-org.ezproxy.auckland.ac.nz/doi/10.1021/acs.accounts.7b00613

The original URL is now split, and periods (".") are replaced by dashes ("-") in the domain name.

I don't know how to specify this in the EZProxy database.

**Comment by tom5760** [comment]
Hello @janerallison!  I just noticed when clicking that second URL, that it redirects to:

https://login.ezproxy.auckland.ac.nz/login?qurl=https://pubs.acs.org%2fdoi%2f10.1021%2facs.accounts.7b00613

Does clicking that link above work for you?  If so, then I can update the URL in the database to:

https://login.ezproxy.auckland.ac.nz/login?qurl=$@

I _think_ that should work.

**Comment by janerallison** [comment]
Ooh yes, that works! (at least, I've tested it by manually typing in the exproxy part for a new url and it took me to the UoA login page and then to the full text). When things weren't working I was having to go via the library which meant I was already essentially logged in which might have something to do with the ezproxy part no longer specifying a login (still no idea about the hyphens). Thank you!

**Comment by tom5760** [comment]
Cool!  I've updated the URL, hopefully that works.  Let me know if you run into any other issues.  Thanks @janerallison!

**Comment by janerallison** [comment]
Brilliant, thank you!

From: Tom Wambold ***@***.***>
Date: Sunday, 6 August 2023 at 02:12
To: tom5760/ezproxy-db ***@***.***>
Cc: janerallison ***@***.***>, Mention ***@***.***>
Subject: Re: [tom5760/ezproxy-db] University of Auckland EZProxy replaces "." with "-" and splits proxied URL (Issue #78)

Cool! I've updated the URL, hopefully that works. Let me know if you run into any other issues. Thanks @janerallison<https://github.com/janerallison>!
