### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by freeaccesstoinfo** [tom5760/ezproxy-db#8]
Brandeis University
Current link: https://go.openathens.net/redirector/brandeis.edu?url=$@

**Comment by tom5760** [comment]
Hello!  This appears to be what [the URL currently is set to in the database](https://github.com/tom5760/ezproxy-db/blob/57a1bfaf245d45a81f287b040ac1c5a17adec0d1/static/proxies.json#L430-L433).  Is there a problem with it?  What is the correct URL?

**Comment by freeaccesstoinfo** [comment]
It used to work but is no longer working. Sorry, I don't have the corrected link. I was hoping someone might be able to help update.

**Comment by tom5760** [comment]
Ah I see.  Yeah, I don't have anything to do with the schools themselves.  Can you contact the school library and see if you can find out what is wrong?
