### ISSUE TITLE
URL removal/de-duplication

### ISSUE THREAD

**Issue by jaredcowing** [tom5760/ezproxy-db#9]
**What is the name of the school / institution?**
Williams

**What is the new proxy URL?**
This URL can be removed from the database, as it is an older URL no longer in use. The entry for "Williams College" also is for our institution and is correct.
(For clarity, the correct URL is https://ezproxy2.williams.edu/login?url=$@ )

**Comment by tom5760** [comment]
Done.  Thanks for the update!
