### ISSUE TITLE
Automatic proxy redirect for certain sites (configured by the user)

### ISSUE THREAD

**Issue by Robert321245** [tom5760/ezproxy-db#90]
Instead needing to click on "Reload page" to access the page using a ezproxy, it would be nice to be able to configure certain sites to always be opened using EXProxy Redirect.

For example, I would like to always access sciencedirect.com, tandfonline.com, nature.com, link-springer.com, onlinelibrary.wiley.com through the an ezproxy. So the extension could have a list where the user can add these sites, and it will be automatically redirected when accessing them.

**Comment by tom5760** [comment]
This is a good idea!  I've been working a bit on the extension again to deal with some Chrome updates, and to possibly implement tom5760/chrome-ezproxy#8.

If you don't mind, could you re-create this issue in the tom5760/chrome-ezproxy repository?  This one is for the database hosted at https://libproxy-db.org/.  Thanks!

**Comment by tom5760** [comment]
Closing in favor of tom5760/chrome-ezproxy#9.
