### ISSUE TITLE
Add Koo Foundation Sun Yat-Sen Cancer Center Library Ezproxy

### ISSUE THREAD

**Issue by htlin222** [tom5760/ezproxy-db#93]
### Name

Koo Foundation Sun Yat-Sen Cancer Center

### URL

https://login.autorpa.kfsyscc.org/login?qurl=$@

### Country

Taiwan

**Comment by tom5760** [comment]
The site has been updated.  Thanks @htlin222!

**Comment by htlin222** [comment]
Your Chrome extension has truly solved our problems. I'm recommending it to all my colleagues at the hospital. Thank you!
