### ISSUE TITLE
Updated Proxy for Cal Poly SLO

### ISSUE THREAD

**Issue by gscott02** [tom5760/ezproxy-db#97]
### Name

California Polytechnic State University

### URL

https://calpoly.idm.oclc.org/login?qurl=$@

### Country

USA

**Comment by gscott02** [comment]
Documentation for this change: https://guides.lib.calpoly.edu/onesearchfaqs/offcampusaccessbookmarklet

**Comment by tom5760** [comment]
Site has been updated.  Thanks for the contribution @gscott02!
