### ISSUE TITLE
Proxy change for LSU Health Sciences Center New Orleans

### ISSUE THREAD

**Issue by rbeale2** [tom5760/ezproxy-db#99]
### Name

LSU Health Sciences Center New Orleans

### URL

https://lsuhscno.idm.oclc.org/login?url=

### Country

USA

**Comment by tom5760** [comment]
The site has been updated.  Thanks @rbeale2!

**Comment by rbeale2** [comment]
Hi Tom,

Thanks so much! I appreciate you taking care of this so quickly.

Thanks again and have a great day!
Rebecca

Rebecca Bealer
Head, Serials/Systems Librarian
LSU Health Sciences Center New Orleans Library
433 Bolivar Street, Box B3-1
New Orleans, LA  70112
504-568-6108
***@***.***


From: Tom Wambold ***@***.***>
Reply-To: tom5760/ezproxy-db ***@***.***>
Date: Thursday, March 14, 2024 at 11:47 AM
To: tom5760/ezproxy-db ***@***.***>
Cc: "Bealer, Rebecca" ***@***.***>, Mention ***@***.***>
Subject: Re: [tom5760/ezproxy-db] Proxy change for LSU Health Sciences Center New Orleans (Issue #99)


*EXTERNAL EMAIL: EVALUATE*

The site has been updated. Thanks @rbeale2<https://github.com/rbeale2>!
